# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
bash --version|sed -n 1p
git --version
echo -e "$(tput setaf 2)Welcome $(id -u -n)"
echo  -e "$(tput setaf 2)Logged in at: $(date)"
